#!/bin/bash

target="$HOME"
exec_name=$0

declare -a packages
for arg in $@; do
    if [[ "$arg" == '-h' ]] || [[ "$arg" == '--help' ]]; then
        # help printout
        echo "usage: $(basename $exec_name) [-h|--help] [--dest=install directory; default: $HOME] [packages; default: all]"
        exit 0
    elif [[ "${arg:0:7}" == "--dest=" ]]; then
        # set install directory
        target="${arg:7}"
    else
        packages+=("$arg")
    fi
done

# if packages empty, add all of them
if [[ ${#packages[@]} -eq 0 ]]; then
    for p in packages/*; do
        packages+=("${p##*/}")
    done
fi

export target=$(readlink -f "$target")
export stow="stow -v --no-folding --target=$target --ignore=install"

# stow each of them, or run their install script
cd packages
for p in ${packages[@]}; do
    if [[ -f "$p/install" ]]; then
        cd "$p"
        ./install
        cd ..
    else
        $stow "$p"
    fi
done
cd ..
